### PR TITLE
Fixes #14590 - Array is merged across YAML settings

### PR DESCRIPTION
**Pull request by lzap**
Only hash is currently merged across YAML files, this patch will add array
support. Required by
https://github.com/theforeman/hammer-cli-foreman-admin/pull/1

### CODE REVIEW

**Comment by tstrachota** [comment]
@lzap looks harmless, could you please add a test for the new behaviour into `test/unit/settings_test.rb` please?

**Comment by lzap** [comment]
I'd swear I created one... :-) Tomorrow.

**Comment by lzap** [comment]
Done!

**Comment by tstrachota** [comment]
:+1: thanks @lzap

**Pull request merged**
