### PR TITLE
Fixes #9507 - highline pinned to < 1.7

### PR DESCRIPTION
**Pull request by tstrachota**

### CODE REVIEW

**Comment by domcleal** [comment]
http://ci.theforeman.org/view/Hammer/job/test_hammer_cli_foreman_pull_request/652/ running

**Comment by domcleal** [comment]
@tstrachota could you rebase onto master please?

(Wow, just noticed the hammer Jenkins jobs still use `patch` rather than git merge.)

**Comment by tstrachota** [comment]
@domcleal done

**Comment by domcleal** [comment]
http://ci.theforeman.org/view/Hammer/job/test_hammer_cli_pull_request/345/ is :white_check_mark:

**Comment by domcleal** [comment]
Thanks!

**Pull request merged**
