### PR TITLE
Refs #36349 - Update minitest version

### PR DESCRIPTION
**Pull request by ofedoren**
Follows https://github.com/theforeman/hammer-cli-foreman/pull/611.

### CODE REVIEW

**Comment by ofedoren** [comment]
Damn, I hoped that it's something on my machine causing this tests to fail...

Well, I've tried to find what caused the tests to fail **randomly**, but failed. I'll leave it here for now.

**Comment by ehelms** [comment]
At a quick glance, the failing tests are all array comparisons. I've always had to solve those by adding `.sort` to ensure that the array has the same order every time.

**Comment by ofedoren** [comment]
I thought about that, but it should not happen at all :/ This is somehow related to the newest minitest version, but I couldn't figure out what could cause the tests fail randomly. The only thing I could think off is there might be a change in code loading or test execution, but again, I couldn't find where/when this happened.

It's also possible we had broken tests all that time, but I doubt it (manually everything works as per tests definitions).

**Comment by ofedoren** [comment]
Closing in favor of https://github.com/theforeman/hammer-cli/pull/372.

**Pull request closed without merging**
