### PR TITLE
Fixes #17819 - Allow adapters print page by page

### PR DESCRIPTION
**Pull request by ofedoren**
TODO:
 - [x] Remove --fields arguments from command context after its invocation.
 - [x] Add tests.
 - [x] ~~Add an explanation of `current_chunk` method~~ Explain `current_chunk` option.

### CODE REVIEW

**Comment by ofedoren** [comment]
Related [PR](https://github.com/theforeman/hammer-cli-foreman/pull/442) that uses this feature is created as well.

**Comment by xprazak2** [comment]
[test hammer]

**Comment by xprazak2** [comment]
Works nicely with the changes in hammer-cli-foreman.

**Comment by xprazak2** [comment]
Thanks!

**Pull request merged**
