### PR TITLE
Fixes #7451 - Review whitespace in extracted strings

### PR DESCRIPTION
**Pull request by ofedoren**

### CODE REVIEW

**Comment by mbacovsky** [comment]
[test]

**Comment by tstrachota** [comment]
[test]

**Comment by tstrachota** [comment]
:+1: good job @ofedoren !
Would you mind doing the same also for `hammer-cli-foreman` ?

**Comment by mbacovsky** [comment]
@ofedoren, we've been too quick merging this and had to revert. I found two issues there:
- the trailing dots in the command descriptions should not be there (see http://projects.theforeman.org/issues/7451#note-1)
- changing the strings broke some tests in hammer-cli-foreman

Could you please reopen this PR and create a new one for the hammer-cli-foreman?

**Pull request merged**
