### PR TITLE
Fixes #36592 - Update minitest version

### PR DESCRIPTION
**Pull request by ofedoren**

### CODE REVIEW

**Comment by ofedoren** [comment]
:green_apple: finally.

Just to be sure:

[test hammer]

**Comment by ofedoren** [comment]
:green_apple:  again :tada:

**Review by adamruzicka — APPROVED** [review]
The diff stat looks a bit scary, but lgtm nevertheless

**Comment by ofedoren** [comment]
> The diff stat looks a bit scary, but lgtm nevertheless

Thanks, main changes are libs update and using `Class.new` instead of `.dup` in tests. Otherwise it's just doing `_()` on all of the assertions since minitest will fail in the future.

**Comment by adamruzicka** [comment]
Thank you @ofedoren !

**Pull request merged**
