### PR TITLE
Refs #11033 - set Enum normalizer on enumerated values

### PR DESCRIPTION
**Pull request by mbacovsky**

### CODE REVIEW

**Comment by domcleal** [comment]
One too many "0"s in the ticket number.

**Comment by tstrachota** [comment]
Nice improvement, @mbacovsky ! Works well.

I have one idea for improvement: update the `description` method to reflect count of allowed alternatives. "One of ..." sounds strange when there's only one value. What do you think?

**Comment by mbacovsky** [comment]
#171 is also related to normalizer clean up and is touching same code so I added it here as a separate commit referencing issue \#11137

**Comment by tstrachota** [comment]
That was quite confusing shuffle. But I understand it saved us one rebase which comes handy today.

:+1: :monkey_face: thanks, @mbacovsky, merging.

**Pull request merged**
