### PR TITLE
Fixes #21359 - Removes code for ruby < 2.1.0

### PR DESCRIPTION
**Pull request by d-m-u**
Hammer no longer supports ruby 2.0, there's no point keeping the old code.

### CODE REVIEW

**Comment by d-m-u** [comment]
@tstrachota thanks! This includes the removal of a method in /test/unit/i18n_test.rb that was for testing the old fast_text gem that I think should also be removed. Lemme know if I'm wrong and I'd be happy to fix!

**Comment by tstrachota** [comment]
[test]

**Comment by tstrachota** [comment]
Thanks for fixing the rest, @d-m-u !
We'll definitely need to remove the tests for `String#format` with this PR: https://github.com/theforeman/hammer-cli/blob/master/test/unit/utils_test.rb#L13 I'm also afraid it might still be used at some places. Would you mind checking it?

**Comment by mmoll** [comment]
What's the status here?

**Comment by tstrachota** [comment]
The PR had wrong label. It's waiting for contributor. Tests are failing and need to be updated as I mentioned in my previous comment (@d-m-u ping).

**Comment by mbacovsky** [comment]
Closing this PR as it was already merged as part of https://github.com/theforeman/hammer-cli/pull/285.

**Pull request closed without merging**
