### PR TITLE
Fixes #36418 - Honor TZ in datetime normalizer

### PR DESCRIPTION
**Pull request by adamruzicka**

### CODE REVIEW

**Review by ofedoren — COMMENTED** [review]
Does it fix the issue?

hammer command TZ:
```sh
$ date
Fri May 19 13:24:00 UTC 2023
```
Browser timezone: Prague
```sh
$ hammer job-invocation create --job-template "Run Command - Script Default" --organization-id "1" --location-id "2" --inputs command=date --search-query "nuka.helole.com" --start-at "2023-05-19 16:24:00"
$ Job invocation 28 created
$ hammer job-invocation info --id 28
$ ID: 28
Description: Run date
Status: queued
Success: N/A
Failed: N/A
Pending: N/A
Missing: 0
Total: N/A
Start: '2023-05-19 18:24:00 +0200'
Randomized ordering: false
Job Category: Commands
Mode: future
Time to pickup: 
Hosts: []
```
ScreenShot-1684503059249

When I log in to check the job invocation list, I see that job will be run in 3 hours instead of 1 hour.

**Comment by ofedoren** [comment]
Looking at the BZ, I think there are two ways to deal with that:
1. Ignore BZ and say that if hammer and the server in different timezones, hammer should specify the server's timezone explicitly. Pros: no changes. Cons: user must explicitly specify TZ.
2. Take hammer input, ask the server for it's timezone, convert hammer input to the server's timezone, send the actual request. Pros: BZ is resolved. Cons: we actually ignore explicitly provided TZ?

**Comment by ofedoren** [comment]
Damn... Is the BZ about hammer and server being in the **same** TZ?..

**Comment by adamruzicka** [comment]
> Is the BZ about hammer and server being in the same TZ?

I think it is about the fact that unless you explicitly include a time zone information in the time string, hammer will assume it is in utc, ignoring the TZ of machine where hammer runs, machine where server runs and TZ the user in Foreman has configured.

Timezones are hell. Verbose & debug output of hammer looks correct, whatever dynflow gets seems correct as well

```
# date                                                                                                                                                                                                            
Fri May 19 13:48:25 UTC 2023

# hammer -v -d job-invocation create --job-template "Run Command - Script Default" --organization-id "1" --location-id "2" --inputs command=date --search-query "nuka.helole.com" --start-at "2023-05-19 16:24:00"
-----B<-----SNIP-----B<-----SNIP
[ INFO 2023-05-19T13:48:59 API] POST /api/job_invocations                                                                                                                                                                                                                               
[DEBUG 2023-05-19T13:48:59 API] Params: {                                                                                                                                                                                                                                               
        "location_id" => 2,                                                                                                                                                                                                                                                             
    "organization_id" => 1,                                                                                                                                                                                                                                                             
     "job_invocation" => {                                                                                                                                                                                                                                                              
            "job_template_id" => 175,                                                                                                                                                                                                                                                   
                     "inputs" => {                                                                                                                                                                                                                                                      
            "command" => "date"                                                                                                                                                                                                                                                         
        },                                                                                                                                                                                                                                                                              
                        "ssh" => {},                                                                                                                                                                                                                                                    
                 "recurrence" => {},                                                                                                                                                                                                                                                    
                 "scheduling" => {                                                                                                                                                                                                                                                      
            "start_at" => "2023-05-19T16:24:00+00:00"                                                                                                                                                                                                                                   
        },
        "concurrency_control" => {},
               "search_query" => "nuka.helole.com",
             "targeting_type" => "static_query"
    }
}
[DEBUG 2023-05-19T13:48:59 API] Headers: {}
[DEBUG 2023-05-19T13:48:59 API] Using authenticator: HammerCLIForeman::Api::SessionAuthenticatorWrapper
[DEBUG 2023-05-19T13:48:59 API] Response: {
                "id" => 7,
       "description" => "Run date",
      "job_category" => "Commands",
      "targeting_id" => 7,
            "status" => 2,
          "start_at" => "2023-05-19 16:24:00 UTC",
      "status_label" => "queued",
          "ssh_user" => nil,
    "time_to_pickup" => nil,
      "dynflow_task" => {
           "id" => "46d0fc92-d6d1-4015-860f-e777e594e8e7",
        "state" => "scheduled"
    },
         "succeeded" => "N/A",
            "failed" => "N/A",
           "pending" => "N/A",
             "total" => "N/A",
           "missing" => 0,
         "targeting" => {
                "bookmark_id" => nil,
               "search_query" => "nuka.helole.com",
             "targeting_type" => "static_query",
                    "user_id" => 4,
        "randomized_ordering" => nil,
                      "hosts" => []
    },
              "task" => {
           "id" => "46d0fc92-d6d1-4015-860f-e777e594e8e7",
        "state" => "scheduled"
    },
              "mode" => "future",
        "scheduling" => {
            "start_at" => "2023-05-19 16:24:00 UTC",
        "start_before" => nil
    }
}

# TZ=America/New_York date
Fri May 19 09:50:08 EDT 2023

# TZ=America/New_York hammer -v -d job-invocation create --job-template "Run Command - Script Default" --organization-id "1" --location-id "2" --inputs command=date --search-query "nuka.helole.com" --start-at "2023-05-19 16:24:00"

[ INFO 2023-05-19T09:49:43 API] POST /api/job_invocations                                                                                                                                                                                                                               
[DEBUG 2023-05-19T09:49:43 API] Params: {                                                                                                                                                                                                                                               
        "location_id" => 2,                                                                                                                                                                                                                                                             
    "organization_id" => 1,                                                                                                                                                                                                                                                             
     "job_invocation" => {                                                                                                                                                                                                                                                              
            "job_template_id" => 175,                                                                                                                                                                                                                                                   
                     "inputs" => {                                                                                                                                                                                                                                                      
            "command" => "date"                                                                                                                                                                                                                                                         
        },                                                                                                                                                                                                                                                                              
                        "ssh" => {},                                                                                                                                                                                                                                                    
                 "recurrence" => {},                                                                                                                                                                                                                                                    
                 "scheduling" => {                                                                                                                                                                                                                                                      
            "start_at" => "2023-05-19T16:24:00-04:00"                                                                                                                                                                                                                                   
        },                                                                                                                                                                                                                                                                              
        "concurrency_control" => {},                                                                                                                                                                                                                                                    
               "search_query" => "nuka.helole.com",                                                                                                                                                                                                                                     
             "targeting_type" => "static_query"                                                                                                                                                                                                                                         
    }
}
[DEBUG 2023-05-19T09:49:43 API] Headers: {}
[DEBUG 2023-05-19T09:49:43 API] Using authenticator: HammerCLIForeman::Api::SessionAuthenticatorWrapper
[DEBUG 2023-05-19T09:49:44 API] Response: {
                "id" => 8,
       "description" => "Run date",
      "job_category" => "Commands",
      "targeting_id" => 8,
            "status" => 2,
          "start_at" => "2023-05-19 20:24:00 UTC",
      "status_label" => "queued",
          "ssh_user" => nil,
    "time_to_pickup" => nil,
      "dynflow_task" => {
           "id" => "9047a32f-fb92-462a-835d-2654e2395351",
        "state" => "scheduled"
    },
         "succeeded" => "N/A",
            "failed" => "N/A",
           "pending" => "N/A",
             "total" => "N/A",
           "missing" => 0,
         "targeting" => {
                "bookmark_id" => nil,
               "search_query" => "nuka.helole.com",
             "targeting_type" => "static_query",
                    "user_id" => 4,
        "randomized_ordering" => nil,
                      "hosts" => []
    },
              "task" => {
           "id" => "9047a32f-fb92-462a-835d-2654e2395351",
        "state" => "scheduled"
    },
              "mode" => "future",
        "scheduling" => {
            "start_at" => "2023-05-19 20:24:00 UTC",
        "start_before" => nil
    }
}
```

16:24 UTC is 18:24 CEST (+02:00)
16:24 EDT is 20:24 UTC

What dynflow sees
```
select ddp.execution_plan_uuid,ddp.start_at from dynflow_delayed_plans as ddp inner join foreman_tasks_tasks as ftt on ftt.external_id = ddp.execution_plan_uuid::varchar where ftt.id in ('9047a32f-fb92-462a-835d-2654e2395351', '46d0fc92-d6d1-4015-860f-e777e594e8e7');
         execution_plan_uuid          |      start_at       
--------------------------------------+---------------------
 dba49f6c-761a-4fdc-af26-b665c78208a7 | 2023-05-19 16:24:00
 5dddaa05-9a60-495c-8625-36b46d7cdfa0 | 2023-05-19 20:24:00
(2 rows)
```

It seem ok all the way up until the ui tries to display it?

**Review by ofedoren — APPROVED** [review]
I'm sorry, @adamruzicka, wrong testing. This patch indeed seems to fix the issue.

**Comment by adamruzicka** [comment]
> I am wondering what the supported or 'right' usage for passing timezone to hammer cli is?

Both are more or less valid approaches, but both do something slightly different.

> I have seen the usage described above: TZ=America/New_York hammer

You can think about this as a default timezone. This timezone will be used if the date *passed in* does not contain any tz information. For example "1986-01-01 08:30" will be treated as `1986-01-01 08:30+00:00` if `TZ=UTC`, or as `1986-01-01 08:30+02:00` if `TZ=Europe/Berlin`.

Note, if it is unset, the system provides a default, usually by means of `/etc/localtime` symlink.

```
$ ls -la /etc/localtime
lrwxrwxrwx. 1 root root 38 Apr 23 13:23 /etc/localtime -> ../usr/share/zoneinfo/America/New_York

$ ruby -e 'require "time"; puts ::Time.parse("1986-01-01 08:30").iso8601'
1986-01-01T08:30:00-05:00

$ TZ=Europe/Berlin ruby -e 'require "time"; puts ::Time.parse("1986-01-01 08:30").iso8601'
1986-01-01T08:30:00+01:00
```

> And I have seen the usage pasing it directly to start-date: %Y-%m-%d %H:%M:%S CEST'

This is unfortunate. Ruby doesn't seem to understand timezones like `CEST`, in which case it seems to silently ignore it and falls back to TZ. It does however understand numeric timezones like "+02:00". Help mentions this in the description of DATETIME

```
# hammer job-invocation create --help | grep DATETIME | tail -n 1
  DATETIME            Date and time in YYYY-MM-DD HH:MM:SS or ISO 8601 format
```

If the date passed in contains timezone information, it is reused in the string being emitted on the other end.

```
$ TZ=Asia/Tokyo ruby -e 'require "time"; puts ::Time.parse("1986-01-01 08:30 CEST").iso8601'
1986-01-01T08:30:00+09:00

$ TZ=Asia/Tokyo ruby -e 'require "time"; puts ::Time.parse("1986-01-01 08:30+02:00").iso8601'
1986-01-01T08:30:00+02:00
```

When this got merged, I had a bit about it in [the community demo](https://www.youtube.com/watch?v=9sI6i7thLYY&t=636s).

**Pull request merged**
