### PR TITLE
Fixes #29093 - change from superficial copy to deep copy of fields

### PR DESCRIPTION
**Pull request by adiabramovitch**

### CODE REVIEW

**Review by yifatmakias — APPROVED** [review]
Looks good and works as expected :)

**Comment by yifatmakias** [comment]
Thanks @adiabramovitch!

**Comment by ekohl** [comment]
I think this caused a regression and has broken our nightlies. https://community.theforeman.org/t/foreman-nightly-rpm-pipeline-1068-failed/23813/2

**Comment by jturel** [comment]
We're also seeing unit test failures in hammer-cli-katello

**Pull request merged**
