### PR TITLE
Add GA to run tests on Ruby 3+

### PR DESCRIPTION
**Pull request by ofedoren**
Probably depends on https://github.com/theforeman/hammer-cli/pull/372.

### CODE REVIEW

**Comment by adamruzicka** [comment]
What's the plan with this and jenkins? Will we have both?

**Comment by ofedoren** [comment]
> What's the plan with this and jenkins?

No idea, I wanted to add Ruby 3 there as well, but decided to try GA first for some reason.

> Will we have both?

I guess for now, yes.

**Review by adamruzicka — APPROVED** [review]
Alright, let's get this in

**Comment by adamruzicka** [comment]
Thank you @ofedoren !

**Pull request merged**
