### PR TITLE
Fixes #33226 - Make API docs params to be the main options

### PR DESCRIPTION
**Pull request by ofedoren**
Requires/Follows https://github.com/theforeman/hammer-cli/pull/350.

I've included that commit for easier testing.

### CODE REVIEW

**Comment by ofedoren** [comment]
@yifatmakias, rebased :)

**Review by yifatmakias — CHANGES_REQUESTED** [review]
Thanks @ofedoren. I am getting many errors when trying to run the tests in hammer-cli-foreman with these changes. Could you fix the tests?

**Comment by ofedoren** [comment]
@yifatmakias, yes and I did it in this PR: https://github.com/theforeman/hammer-cli-foreman/pull/580

**Comment by yifatmakias** [comment]
> @yifatmakias, yes and I did it in this PR: [theforeman/hammer-cli-foreman#580](https://github.com/theforeman/hammer-cli-foreman/pull/580)

oh I am sorry I missed this.

**Review by yifatmakias — APPROVED** [review]
Thanks @ofedoren. looks good, works for me.

**Pull request merged**
