### PR TITLE
Fixes #19676 - saving defaults from hammer shell

### PR DESCRIPTION
**Pull request by tstrachota**
See the linked redmine issue for reproducer steps.

### CODE REVIEW

**Comment by mbacovsky** [comment]
@tstrachota, the patch looks good. But I'm not sure it fixes the whole problem. When updating defaults in the hammer shell, the hammer instance defaults are not updated. Just the config file. 
```
hammer> defaults list
----------------|---------------------
PARAMETER       | VALUE               
----------------|---------------------
----------------|---------------------

hammer> defaults add --param-name location-id --provider foreman
Added location-id default-option with value that will be generated from the server.

hammer> defaults list
----------------|---------------------
PARAMETER       | VALUE               
----------------|---------------------
----------------|---------------------
```
The config looks good now and after reloading the shell all is right.
```
$ cat ~/.hammer/defaults.yml 
---
:defaults:
  :location-id:
    :provider: foreman
```

The way how the `update_defaults_file` works is weird. It loads the config, update it and store regardless what the instance content is (settings can be provided in constructor so it can be completely different from the config file content). While the defaults instance in the shell persists it is not reloaded and miss the new data. I'd suggest to change the `update_defaults_file`  to update `@defaults_settings` and overwrite the config file with it. What do you think?

**Comment by tstrachota** [comment]
@mbacovsky added a commit that fixes behavior in shell. Should be squashed before merge.

**Comment by ares** [comment]
Fixes the problem for me, code looks good to me

**Comment by tstrachota** [comment]
@mbacovsky I've addressed your comments, can you please re-review?

**Comment by mbacovsky** [comment]
:+1: Thanks @tstrachota, :hammer:  :shell: works great now!

**Pull request merged**
