### PR TITLE
Fixes #27899 - Allow schema building for custom options

### PR DESCRIPTION
**Pull request by ofedoren**

### CODE REVIEW

**Comment by shiramax** [comment]
@ofedoren what do you think about this help:

Option details:
  Following parameters accept format defined by its schema (bold are required, parameter_name and value must be a string):

  --typed-parameters  "name=<parameter_name>\,value=<parameter_value>\,parameter_type=[string || int ...]]  "

**Comment by ofedoren** [comment]
@shiramax, thanks for your effort to make UX better!

I agree that it will help users, but what if we go further and show something even more verbose?
```
  Following parameters accept format defined by its schema (bold are required; <> contain acceptable type; [] contain acceptable value):

  --typed-parameters  "name=<string>\,value=<string>\,parameter_type=[string|boolean|integer|real|array|hash|yaml|json]\,hidden_value=[true|false|1|0], ... "
```

Please tell me what do you think about that :)

**Comment by shiramax** [comment]
@ofedoren , looks good !

**Comment by ofedoren** [comment]
@shiramax, updated :) I've added a way to show mentioned help, so when you have time please check it (with https://github.com/theforeman/hammer-cli-foreman/pull/448 for example) and tell me if it's better.

**Pull request merged**
