### PR TITLE
fixes #14436 - added exception handling while parsing configuration file.

### PR DESCRIPTION
**Pull request by Akasurde**
Notifies user about syntax error in given configuration file
provided.

Fixes: http://projects.theforeman.org/issues/14436

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

### CODE REVIEW

**Comment by domcleal** [comment]
Administrative note: there's a standard format of `fixes #14436 - added [..]` for commit messages linked to our issue tracker to link the two automatically, see http://theforeman.org/contribute.html#SubmitPatches for details. You may want to `git commit --amend` the message to suit.

**Comment by mbacovsky** [comment]
@Akasurde, thanks for the patch. 
Could you please preserve and output the original error message it can be helpful for the user. I'd prefer to get something like: Couldn't load configuration file '/home/vagrant/.hammer/cli_config.yml': did not find expected key while parsing a block mapping at line 2 column 1
Another reason is that we are catching generic exception here and the reasons for failure during reading config may vary.

**Comment by mbacovsky** [comment]
[test]

**Comment by tstrachota** [comment]
@Akasurde I opened https://github.com/theforeman/hammer-cli/pull/211 where I'm addressing @mbacovsky's comments.

**Comment by Akasurde** [comment]
@tstrachota Thanks for update. Please go ahead with #211

**Comment by mbacovsky** [comment]
Closed. The original commit merged as part of #211. Thanks @Akasurde, @tstrachota.

**Pull request closed without merging**
