### PR TITLE
Make update-po target working on Ubuntu

### PR DESCRIPTION
**Pull request by stejskalleos**

### CODE REVIEW

**Comment by stejskalleos** [comment]
It's for translation github action: https://github.com/stejskalleos/hammer-cli-foreman-google/blob/akcion/.github/workflows/translations_pull.yml

**Comment by ofedoren** [comment]
After https://github.com/theforeman/hammer-cli/pull/366 it's better to use rake task now: `bundle exec rake tx:update`. Would you mind to update https://github.com/theforeman/hammer-cli/blob/master/lib/hammer_cli/i18n/find_task.rb#L69 as well? Or have you tried the new command on Ubuntu?

**Comment by stejskalleos** [comment]
Huh I didn't know that there is a rake task for it. So what's the correct way of updating strings in hammer plugins? Is it documented somewhere?

**Comment by stejskalleos** [comment]
The rake task fails on Ubuntu with:
```
locale/hammer_cli_foreman_google.po" for reading: No such file or directory
rake aborted!
Command failed with status (1): [msgcat --use-first --no-location /root/ham...]
/root/hammer-cli/lib/hammer_cli/i18n/find_task.rb:69:in `block (3 levels) in define'
/root/hammer-cli/lib/hammer_cli/i18n/find_task.rb:67:in `each'
/root/hammer-cli/lib/hammer_cli/i18n/find_task.rb:67:in `block (2 levels) in define'
/root/hammer-cli/lib/hammer_cli/i18n/find_task.rb:88:in `block (2 levels) in define'
/root/.rbenv/versions/2.7.8/bin/bundle:23:in `load'
/root/.rbenv/versions/2.7.8/bin/bundle:23:in `<main>'
```

**Comment by ofedoren** [comment]
@stejskalleos, I've just checked the rake task on Ubuntu and it just works™. Have you `sudo apt install gettext`?

**Comment by stejskalleos** [comment]
```
apt install gettext

gettext is already the newest version (0.21-11).
```
On Ubuntu 23.04 it fails with the error in the comment above. `make tx-pull` works fine

**Comment by ofedoren** [comment]
Well, it seems that makefile fails because it expects `bash` instead of `dash`, but the rake task should work since we don't use any substitution, just full path to the files...

I've checked on Ubuntu 20.04, but I'll try to re-check on Ubuntu 23.04...

**Comment by ofedoren** [comment]
@stejskalleos, I've re-checked on Ubuntu 23.04 (just to make sure) and it still works:
ScreenShot-1696246087329
The only possible differences may be in what I have installed on the OS:
 - `sudo apt-get update && sudo apt install ruby-dev build-essential gettext ruby-bundler`
Also I use the new `tx` tool instead of the old one:
 - `curl -o- https://raw.githubusercontent.com/transifex/cli/master/install.sh | bash` (https://developers.transifex.com/docs/cli#installing-with-a-script-linuxmac)

**Comment by stejskalleos** [comment]
Hmm, so it's something on my setup, closing the PR

**Pull request closed without merging**
