### PR TITLE
refs #11452 - bump required apipie-bindings version

### PR DESCRIPTION
**Pull request by mmoll**
and delete direct dependency to rest-client, as apipie-bindings already is pulling that in.

### CODE REVIEW

**Comment by mbacovsky** [comment]
Looks good, I'll wait with merging this till bindings are packaged, so that we don't break nightlies.
DEB: https://github.com/theforeman/foreman-packaging/pull/783, no RPM yet.

**Comment by domcleal** [comment]
RPMs were done in https://github.com/theforeman/foreman-packaging/pull/784, there are no nightly Hammer builds for Debian.

**Comment by mbacovsky** [comment]
I missed that one, thanks @domcleal

**Comment by mbacovsky** [comment]
:+1: merging, thanks @mmoll !

**Pull request merged**
