### PR TITLE
Fixes #11184 : Pull in the downstream translations

### PR DESCRIPTION
**Pull request by bkearney**
Detailed Summary Can be found at https://gist.github.com/bkearney/65cc0f36bdfdf94e079e

### CODE REVIEW

**Comment by domcleal** [comment]
How are the string changes going to be reviewed?  Maybe contact our translation teams?

**Comment by bkearney** [comment]
Happy to... Is there an email group I can use?

-- bk
Sent with thumbs

**Comment by domcleal** [comment]
There isn't.

**Comment by bkearney** [comment]
@domcleal I reached out to the active contributors on transifex, and also left a public message at https://www.transifex.com/organization/foreman/team/114/discussions/. Should I also send to the user list, or do you think the dev list is acceptable for now?

**Comment by mbacovsky** [comment]
:+1: I'll fix the white space during the merge

**Comment by bkearney** [comment]
@mbacovsky to confirm, have you also pushed these to transifex?

**Pull request merged**
